# Generated by Django 3.1.2 on 2020-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_auto_20201027_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
