# Generated by Django 3.1.2 on 2020-10-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_auto_20201027_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
