# Generated by Django 3.1.2 on 2020-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_remove_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
