# Generated by Django 3.1.2 on 2020-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
