# Generated by Django 3.1.2 on 2020-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0008_auto_20201028_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
