# Generated by Django 3.1.2 on 2020-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0009_auto_20201028_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
