# Generated by Django 3.1.2 on 2020-10-28 13:33

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0011_auto_20201028_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='reviews',
            field=models.CharField(blank=True, default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='My Project', max_length=60),
        ),
    ]
