# Generated by Django 3.1.2 on 2020-10-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0012_auto_20201028_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='image',
        ),
    ]
