# Generated by Django 3.1.2 on 2020-10-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0013_auto_20201028_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='img',
        ),
    ]
